import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { NeoBrutalismProvider } from "./components/ui/neobrutalism-provider";

const overusedGrotesk = localFont({
  src: './fonts/OverusedGroteskRoman-VF.ttf',
  variable: '--font-overused-grotesk',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overusedGrotesk.variable} antialiased`}
      >
        <NeoBrutalismProvider>
          {children}
        </NeoBrutalismProvider>
      </body>
    </html>
  );
}
